name: portfolio_website_django(build and push image)

on:
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: purvakoushik/django_portfolio:latest

    - name: docker run image
      run: docker run -d -p8080:8000 purvakoushik/django_portfolio:latest

    - name: docker ps image
      run: docker ps -a
    
    - name: docker push image
      run: docker push purvakoushik/django_portfolio:latest
